### ISSUE TITLE
Read Performance concurrency issue

### ISSUE THREAD

**Issue by l3r8yJ** [eo-cqrs/xfake#22]
https://github.com/eo-cqrs/xfake/blob/ecd9054d28728e9b8653e61b70c4b81580ca3d56/src/main/java/io/github/eocqrs/xfake/InFile.java#L85-L95

better replace to 
```java
...
final ReentrantReadWriteLock rwlock = new ReentrantReadWriteLock();
...
 public XML xml() throws Exception { 
   this.rwlock.readLock().lock()
     try {
       return new XMLDocument( 
         new TextOf( 
           new File( 
             this.name 
           ) 
         ).asString() 
       ); 
     } finally {
       this.rwlock.readLock.unlock();
     }
   }
 } 
```

**Comment by zoeself** [comment]
@l3r8yJ thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by zoeself** [comment]
@h1alexbel this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2023-06-05T06:12:21.434266``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by h1alexbel** [comment]
@l3r8yJ nice, I will try to apply it!

**Comment by 0pdd** [comment]
@l3r8yJ the puzzle [#26](https://github.com/eo-cqrs/xfake/issues/26) is still not solved.

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Comment by 0pdd** [comment]
@l3r8yJ the only puzzle [#26](https://github.com/eo-cqrs/xfake/issues/26) is solved here.
